---
title: "Explore_Data"
output: html_document
date: "2026-01-29"
---

```{r LoadLibraries, message = FALSE, error = FALSE}
# Load in needed libraries
library(ohdsilab)
library(DatabaseConnector)
library(keyring)
library(dplyr)
library(keyring)
library(ROhdsiWebApi)
library(CohortGenerator)
```

```{r}
# Define constants
atlas_url <- "https://atlas.roux-ohdsi-prod.aws.northeastern.edu/WebAPI"
cdm_schema <- "omop_cdm_53_pmtx_202203"
write_schema <- paste0("work_", keyring::key_get("db_username"))
```

```{r}
# Define path to JDBC driver
Sys.setenv("DATABASECONNECTOR_JAR_FOLDER" = "D:/Users/washburn.e/Downloads/redshift-jdbc42-2.2.2")

# Establish a connection to the database
connectionDetails <- createConnectionDetails(
    dbms = "redshift",
    server = "ohdsi-lab-redshift-cluster-prod.clsyktjhufn7.us-east-1.redshift.amazonaws.com/ohdsi_lab",
    port = 5439,
    user = keyring::key_get("db_username"),
    password = keyring::key_get("db_password"))

# Connect to the database to save the variable "con"
con <- DatabaseConnector::connect(connectionDetails)

# See if connection is successful
if (isTRUE(DatabaseConnector::dbIsValid(con))) print("Connected Successfully")
```
```{r}
# Make it easier for some r functions to find the database
options(con.default.value = con)
options(schema.default.value = cdm_schema)
options(write_schema.default.value = write_schema)
```

```{r}
# Authorize the API for accessing ATLAS from R 
ROhdsiWebApi::authorizeWebApi(
    atlas_url,
    authMethod = "db",
    webApiUsername = keyring::key_get("atlas_username"),
    webApiPassword = keyring::key_get("atlas_password"))
```

```{r}
# Define my created cohort ID
cohortId <- 5276

# Create a cohortDefinitionSet 
cohortDefinitionSet <- ROhdsiWebApi::exportCohortDefinitionSet(
    baseUrl = atlas_url,
    cohortIds = cohortId)
```

```{r}
# Create a name for this cohort
cohortTableNames <- getCohortTableNames(cohortTable = "EZW_Cohort")
```

```{r}
# Create empty tables in the {mySchema}.cohort table
createCohortTables(
    connectionDetails = connectionDetails,
    cohortTableNames = cohortTableNames,
    cohortDatabaseSchema = write_schema)
```

```{r}
# Add everyone from the database to the cohort
cohortsGenerated <- generateCohortSet(
    connectionDetails = connectionDetails,
    cdmDatabaseSchema = cdm_schema,
    cohortDatabaseSchema = write_schema,
    cohortTableNames = cohortTableNames,
    cohortDefinitionSet = cohortDefinitionSet)
```

If I want to visually see the new table in my schema, I can connect to the database and use the **Connections** pane in the top right of RStudio: 

con =  DatabaseConnector::connect(
  dbms = "redshift",
  server = "ohdsi-lab-redshift-cluster-prod.clsyktjhufn7.us-east-1.redshift.amazonaws.com/ohdsi_lab",
  port = 5439,
  user = keyring::key_get("db_username"),
  password = keyring::key_get("db_password"))

```{r}
# Create my cohort table 
cohort <- tbl(
    con,
    inDatabaseSchema(write_schema, "EZW_Cohort")) |>
    select(person_id = subject_id, cohort_start_date, cohort_end_date)

# Define the 'person' table connection 
person <- tbl(con, inDatabaseSchema(cdm_schema, "person"))

# Create my demographics table 
demographics <- cohort |> 
  inner_join(person, by = "person_id") |> 
  select(
    person_id,
    cohort_start_date,
    cohort_end_date,
    year_of_birth,
    gender_concept_id,
    gender_source_value,
    location_id)

# Define the 'location' table connection 
locations <- tbl(con, inDatabaseSchema(cdm_schema, "location"))

# Create my demographics with ZIP table 
demographics_with_zip <- demographics |> 
  left_join(locations, by = "location_id") |> 
  select(
    person_id,
    cohort_start_date,
    cohort_end_date,
    year_of_birth,
    gender_source_value,
    address_1,
    address_2,
    zip, # Full ZIP or ZIP-3 for ADI/SVI matching
    state)

# Define the 'condition_occurrence' table connection 
condition_occurrence <- tbl(con, inDatabaseSchema(cdm_schema, "condition_occurrence"))

conditions <- cohort |> 
  inner_join(condition_occurrence, by = "person_id") |> 
  select(person_id,
    condition_occurrence_id,
    condition_concept_id,  # For diabetes, HTN, dyslipidemia
    condition_start_date,
    condition_end_date,
    condition_type_concept_id,
    condition_source_value)

# Define the 'drug-exposure' table connection 
drug_exposure <- tbl(con, inDatabaseSchema(cdm_schema, "drug_exposure"))

drugs <- cohort |> 
  inner_join(drug_exposure, by = "person_id") |> 
  select(
    person_id,
    drug_exposure_id,
    drug_concept_id,
    drug_exposure_start_date,
    drug_exposure_end_date,
    drug_type_concept_id,
    quantity,
    days_supply,  # CRITICAL for PDC calculation
    refills,
    drug_source_value,
    provider_id  # CRITICAL: Links to provider quality rankings
  )

# Define the 'payer_plan_period' table connection 
payers <- tbl(con, inDatabaseSchema(cdm_schema, "payer_plan_period"))

payer <- cohort |> 
  inner_join(payers, by = "person_id") |> 
  select(
    person_id,
    payer_plan_period_id,
    payer_plan_period_start_date,
    payer_plan_period_end_date,
    payer_source_value,  # Commercial, HMO, PPO
    plan_source_value,  # High deductible vs traditional
    payer_concept_id
  )

# Define the 'provider' table connection 
providers <- tbl(con, inDatabaseSchema(cdm_schema, "provider"))

drug_providers <- drugs |> 
  filter(!is.na(provider_id)) |>
  inner_join(providers, by = "provider_id") |> 
  select(
    person_id,
    provider_id,
    npi,  # CRITICAL: Match to NPPES
    specialty_concept_id,
    specialty_source_value) |>
  distinct()

# Define the 'visit_occurrence' table connection 
visits <- tbl(con, inDatabaseSchema(cdm_schema, "visit_occurrence"))

# Get providers from visits (attributed providers)
visit_providers <- visits |> 
  filter(!is.na(provider_id)) |>
  inner_join(providers, by = "provider_id") |> 
  select(
    person_id,
    provider_id,
    specialty_concept_id,
    specialty_source_value
  ) |>
  distinct()

visit <- cohort |> 
  inner_join(visits, by = "person_id") |> 
  select(
    person_id,
    visit_occurrence_id,
    visit_concept_id,  # Outpatient, ER, inpatient
    visit_start_date,
    visit_end_date,
    visit_type_concept_id,
    care_site_id,
    provider_id)

# Define the 'observation_period' table connection 
observation_table <- tbl(con, inDatabaseSchema(cdm_schema, "observation_period"))

enrollment <- cohort |> 
  inner_join(observation_table, by = "person_id") |> 
  select(
    person_id,
    observation_period_start_date,
    observation_period_end_date,
    period_type_concept_id)
```

```{r}
demographics
demographics_with_zip
conditions
drugs 
payer
drug_providers
visit_providers
visit
enrollment
```

